version: '2'

services:
  php-cli:
    build: docker/php74-cli
    container_name: php74-cli-task3
    working_dir: "/var/code/"
    links:
      - redis
    volumes:
      - ./:/var/code:rw,cached
    networks:
      - app-network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge